
cameras:
  - url: "rtsp://consumer:IyKv4uY7%g^8@10.199.51.162/axis-media/media.amp?streamprofile=H264-OpenCV-Optimized"
    camera_id: "mlk-peeples-cam-3"
  - url: "rtsp://consumer:IyKv4uY7%g^8@10.199.51.228/axis-media/media.amp?streamprofile=H264-OpenCV-Optimized"
    camera_id: "mlk-central-cam-2"
  - url: "rtsp://consumer:IyKv4uY7%g^8@10.199.51.155/axis-media/media.amp?streamprofile=H264-OpenCV-Optimized"
    camera_id: "mlk-douglas-cam-2"
  - url: "rtsp://consumer:IyKv4uY7%g^8@10.199.51.222/axis-media/media.amp?streamprofile=H264-OpenCV-Optimized"
    camera_id: "mlk-peeples-cam-1"
  - url: "rtsp://consumer:IyKv4uY7%g^8@10.199.51.247/axis-media/media.amp?streamprofile=H264-OpenCV-Optimized"
    camera_id: "mlk-magnolia-cam-2"
  - url: "rtsp://consumer:IyKv4uY7%g^8@10.199.51.166/axis-media/media.amp?streamprofile=H264-OpenCV-Optimized"
    camera_id: "mlk-georgia-cam-1"
  - url: "rtsp://consumer:IyKv4uY7%g^8@10.199.51.218/axis-media/media.amp?streamprofile=H264-OpenCV-Optimized"
    camera_id: "mlk-lindsay-cam-2"
  - url: "rtsp://consumer:IyKv4uY7%g^8@10.199.51.224/axis-media/media.amp?streamprofile=H264-OpenCV-Optimized"
    camera_id: "mlk-houston-cam-1"
  - url: "rtsp://consumer:IyKv4uY7%g^8@10.199.51.242/axis-media/media.amp?streamprofile=H264-OpenCV-Optimized"
    camera_id: "mlk-douglas-cam-1"
  - url: "rtsp://consumer:IyKv4uY7%g^8@10.199.51.165/axis-media/media.amp?streamprofile=H264-OpenCV-Optimized"
    camera_id: "mlk-georgia-cam-3"
  - url: "rtsp://consumer:IyKv4uY7%g^8@10.199.51.159/axis-media/media.amp?streamprofile=H264-OpenCV-Optimized"
    camera_id: "mlk-houston-cam-2"
  - url: "rtsp://consumer:IyKv4uY7%g^8@10.199.51.248/axis-media/media.amp?streamprofile=H264-OpenCV-Optimized"
    camera_id: "mlk-magnolia-cam-1"
  - url: "rtsp://consumer:IyKv4uY7%g^8@10.199.51.216/axis-media/media.amp?streamprofile=H264-OpenCV-Optimized"
    camera_id: "mlk-georgia-cam-2"
  - url: "rtsp://consumer:IyKv4uY7%g^8@10.199.51.223/axis-media/media.amp?streamprofile=H264-OpenCV-Optimized"
    camera_id: "mlk-peeples-cam-2"
  - url: "rtsp://consumer:IyKv4uY7%g^8@10.199.51.229/axis-media/media.amp?streamprofile=H264-OpenCV-Optimized"
    camera_id: "mlk-central-cam-1"
  - url: "rtsp://consumer:IyKv4uY7%g^8@10.199.51.219/axis-media/media.amp?streamprofile=H264-OpenCV-Optimized"
    camera_id: "mlk-lindsay-cam-1"
  - url: "rtsp://consumer:IyKv4uY7%g^8@10.199.51.225/axis-media/media.amp?streamprofile=H264-OpenCV-Optimized"
    camera_id: "mlk-houston-cam-3"
  - url: "rtsp://consumer:IyKv4uY7%g^8@10.199.51.246/axis-media/media.amp?streamprofile=H264-OpenCV-Optimized"
    camera_id: "mlk-magnolia-cam-3"
  - url: "rtsp://consumer:IyKv4uY7%g^8@10.199.51.147/axis-media/media.amp?streamprofile=H264-OpenCV-Optimized"
    camera_id: "mlk-lindsay-cam-3"
  - url: "rtsp://consumer:IyKv4uY7%g^8@10.199.51.170/axis-media/media.amp?streamprofile=H264-OpenCV-Optimized"
    camera_id: "mlk-central-cam-3"
  - url: "rtsp://consumer:IyKv4uY7%g^8@10.199.51.171/axis-media/media.amp?streamprofile=H264-OpenCV-Optimized"
    camera_id: "mlk-douglas-cam-3"
